name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SCD_DEPLOY_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@45.159.248.213 '
        # Navigate to the application directory or clone repository if not present
        if [ ! -d "/usr/apps/sc-downloader/.git" ]; then
          sudo git clone https://github.com/EliteUser/scd.git /usr/apps/sc-downloader
        fi
        cd /usr/apps/sc-downloader
        sudo git pull origin master

        # Build the Docker image
        sudo docker build -t sc-downloader .

        # Stop and remove the existing container if it exists
        if sudo docker ps -q -f name=sc-downloader; then
          sudo docker stop sc-downloader
          sudo docker rm sc-downloader
        fi

        # Run the new container
        sudo docker run -d -p 3000:3000 --name sc-downloader sc-downloader
        '